version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_TCP_PORT=$DB_PORT
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: