CREATE TABLE IF NOT EXISTS Courses(
id INT AUTO_INCREMENT PRIMARY KEY,
owner_id INT NOT NULL,
trainer_id INT,
title NVARCHAR(100) NOT NULL,
language ENUM('POLISH', 'ENGLISH') DEFAULT 'POLISH',
level ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERT') DEFAULT 'BEGINNER',
location NVARCHAR(100) NOT NULL,
FOREIGN KEY(owner_id) REFERENCES Users(id) ON DELETE CASCADE,
FOREIGN KEY(trainer_id) REFERENCES Users(id) ON DELETE SET NULL
);