CREATE TABLE IF NOT EXISTS Enrolled(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
course_id INT NOT NULL,
FOREIGN KEY(user_id) REFERENCES Users(id) ON DELETE CASCADE,
FOREIGN KEY(course_id) REFERENCES Courses(id) ON DELETE CASCADE
);