CREATE TABLE IF NOT EXISTS Users(
id INT AUTO_INCREMENT PRIMARY KEY, 
username VARCHAR(255) NOT NULL,
password VARCHAR(60) NOT NULL,
firstName NVARCHAR(50) NOT NULL,
lastName NVARCHAR(50) NOT NULL,
email NVARCHAR(255) NOT NULL,
role ENUM('REGULAR', 'CREATOR', 'ADMIN') DEFAULT 'REGULAR');